<a href="https://colab.research.google.com/github/NishanRegmi/Pytorch/blob/main/dataset%26dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Dataset & DataLoader**

Dataset and dataloader are core abstractions in PyTorch that decouple how you define your data from how you efficiently iterate over it in training loops.

**Dataset class**

The dataset class is essentially a blueprint. When you create a custom dataset, you decide how data is loaded and returned.

It defines:

1.  __init__() which tells how data should be loaded.

2.  __len__() which returns the total number of samples.

3.  __getitem__(index) which returns the data (and label) at the given index.

**DataLoader Class**

The dataloader wraps a dataset and handles batching, shuffling and parallel loading for you.

In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
from numpy.random import rand
X, y = make_classification(
    n_samples=10, n_features=2,
    n_informative=2,n_redundant=0,
    n_classes=2,random_state=42
)

In [ ]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
#convert data into pytorch tensor
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [ ]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [ ]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
from torch.utils.data import DataLoader, Dataset

In [ ]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [ ]:
dataset = CustomDataset(X, y)

In [ ]:
len(dataset)

10

In [ ]:
dataset[4]

(tensor([-1.9629, -0.9923]), tensor(0))

In [ ]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [ ]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print('-'*50)

tensor([[ 1.8997,  0.8344],
        [ 1.7273, -1.1858]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.7774,  1.5116]])
tensor([0, 1])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-1.9629, -0.9923]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-0.7206, -0.9606]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------

Using dataloader and dataset in breast cancer dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv('/content/sample_data/breast_cancer.csv')

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
df.shape

(569, 31)

In [7]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [8]:
#split into train test
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.3, random_state=41)

In [9]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
462,14.40,26.99,92.25,646.1,0.06995,0.05223,0.03476,0.01737,0.1707,0.05433,...,15.40,31.98,100.40,734.6,0.10170,0.1460,0.1472,0.05563,0.2345,0.06464
262,17.29,22.13,114.40,947.8,0.08999,0.12730,0.09697,0.07507,0.2108,0.05464,...,20.39,27.24,137.90,1295.0,0.11340,0.2867,0.2298,0.15280,0.3067,0.07484
215,13.86,16.93,90.96,578.9,0.10260,0.15170,0.09901,0.05602,0.2106,0.06916,...,15.75,26.93,104.40,750.1,0.14600,0.4370,0.4636,0.16540,0.3630,0.10590
286,11.94,20.76,77.87,441.0,0.08605,0.10110,0.06574,0.03791,0.1588,0.06766,...,13.24,27.29,92.20,546.1,0.11160,0.2813,0.2365,0.11550,0.2465,0.09981
509,15.46,23.95,103.80,731.3,0.11830,0.18700,0.20300,0.08520,0.1807,0.07083,...,17.11,36.33,117.70,909.4,0.17320,0.4967,0.5911,0.21630,0.3013,0.10670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,11.62,18.18,76.38,408.8,0.11750,0.14830,0.10200,0.05564,0.1957,0.07255,...,13.36,25.40,88.14,528.1,0.17800,0.2878,0.3186,0.14160,0.2660,0.09270
407,12.85,21.37,82.63,514.5,0.07551,0.08316,0.06126,0.01867,0.1580,0.06114,...,14.40,27.01,91.63,645.8,0.09402,0.1936,0.1838,0.05601,0.2488,0.08151
243,13.75,23.77,88.54,590.0,0.08043,0.06807,0.04697,0.02344,0.1773,0.05429,...,15.01,26.34,98.00,706.0,0.09368,0.1442,0.1359,0.06106,0.2663,0.06321
321,20.16,19.66,131.10,1274.0,0.08020,0.08564,0.11550,0.07726,0.1928,0.05096,...,23.06,23.03,150.20,1657.0,0.10540,0.1537,0.2606,0.14250,0.3055,0.05933
80,11.45,20.97,73.81,401.5,0.11020,0.09362,0.04591,0.02233,0.1842,0.07005,...,13.11,32.16,84.53,525.1,0.15570,0.1676,0.1755,0.06127,0.2762,0.08851

In [10]:
#using standard scaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[ 0.09663669,  1.81518286,  0.03025334, ..., -0.91588908,
        -0.9306256 , -1.11946083],
       [ 0.94487732,  0.6602288 ,  0.97457356, ...,  0.61800943,
         0.33385928, -0.52281717],
       [-0.0618581 , -0.57552452, -0.02474319, ...,  0.81690952,
         1.31987727,  1.29402128],
       ...,
       [-0.09414408,  1.04996638, -0.12791497, ..., -0.83017262,
        -0.37369182, -1.20310793],
       [ 1.78724777,  0.07324597,  1.68654412, ...,  0.45541651,
         0.31284291, -1.4300665 ],
       [-0.76921447,  0.38456075, -0.75589858, ..., -0.82685761,
        -0.20030677,  0.27680233]])

In [12]:
#label encoder
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
import torch
import torch.nn as nn

In [14]:
#convert into pytorch tensor
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [15]:
from torch.utils.data import Dataset, DataLoader

In [16]:
class Customdataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [17]:
train_dataset = Customdataset(X_train_tensor, y_train_tensor)
test_dataset = Customdataset(X_test_tensor, y_test_tensor)

In [18]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loadaer = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [19]:
#defining a model
class SimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 5),
        nn.ReLU(),
        nn.Linear(5, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [20]:
#parameters
learning_rate = 0.1
epochs = 25

In [21]:
#create model
model = SimpleNN(X_train_tensor.shape[1])

#define optimizer
opt = torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loss function
loss_function = nn.BCELoss()

In [22]:
#define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    #forward pass
    y_pred = model(batch_features)

    #loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1, 1))

    #clear gradient
    opt.zero_grad()

    #backward pass
    loss.backward()

    #parameters update
    opt.step()

  #print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.638890266418457
Epoch: 2, Loss: 0.6582350134849548
Epoch: 3, Loss: 0.42737966775894165
Epoch: 4, Loss: 0.3659515976905823
Epoch: 5, Loss: 0.27032116055488586
Epoch: 6, Loss: 0.17654624581336975
Epoch: 7, Loss: 0.4167141020298004
Epoch: 8, Loss: 0.14983177185058594
Epoch: 9, Loss: 0.25434932112693787
Epoch: 10, Loss: 0.2543896436691284
Epoch: 11, Loss: 0.11244793981313705
Epoch: 12, Loss: 0.034874532371759415
Epoch: 13, Loss: 0.17525675892829895
Epoch: 14, Loss: 0.1897549331188202
Epoch: 15, Loss: 0.22461183369159698
Epoch: 16, Loss: 0.5000758171081543
Epoch: 17, Loss: 0.3199545741081238
Epoch: 18, Loss: 0.14391295611858368
Epoch: 19, Loss: 0.061622608453035355
Epoch: 20, Loss: 0.14053821563720703
Epoch: 21, Loss: 0.38317781686782837
Epoch: 22, Loss: 0.3304808735847473
Epoch: 23, Loss: 0.07089296728372574
Epoch: 24, Loss: 0.07202606648206711
Epoch: 25, Loss: 0.0860813781619072

In [23]:
#evaluation
#Model evaluation using testloader
model.eval() #set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loadaer:
    #forward pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    #calculate accuracy for current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

#calculate overall accuracy
overall_accuracy = (sum(accuracy_list)/len(accuracy_list))*100
print(f"Overall Accuracy is {overall_accuracy:.4f}%")

Overall Accuracy is 98.9583%