<a href="https://colab.research.google.com/github/NishanRegmi/Pytorch/blob/main/NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NN Module**

The torch.nn module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively.

Key component of torch.nn

1. Modules(layers):
2. Activatio function:
3. Loss Functions:
4. Container Modules
5. Regularization and dropout

In [3]:
import torch
import torch.nn as nn

In [4]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  #forward pass
  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [5]:
#create dataset
features = torch.rand(10, 5)

#create model
model = Model(features.shape[1])

#call model for forward pass
#model.forward(features) #this also works
model(features)

tensor([[0.4726],
        [0.4176],
        [0.4229],
        [0.4939],
        [0.4713],
        [0.4660],
        [0.4856],
        [0.4927],
        [0.4867],
        [0.5163]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear.weight

Parameter containing:
tensor([[ 0.0526, -0.1538,  0.3663,  0.1791, -0.1435]], requires_grad=True)

In [7]:
pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [8]:
from torchinfo import summary
summary(model, input_size=(10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

Creating new neural network with more hidden layer.

In [9]:
import torch
import torch.nn as nn

In [10]:
class NNmodule(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [11]:
#create dataset
features = torch.rand(10, 5)

#create model
model = NNmodule(features.shape[1])

model(features)

tensor([[0.4357],
        [0.4280],
        [0.4295],
        [0.4248],
        [0.4267],
        [0.4244],
        [0.4326],
        [0.4325],
        [0.4398],
        [0.4422]], grad_fn=<SigmoidBackward0>)

In [13]:
#weight
print(model.linear1.weight)
print(model.linear1.bias)
print(model.linear2.weight)
print(model.linear2.bias)

Parameter containing:
tensor([[-0.0522, -0.1534,  0.1119, -0.1058, -0.0203],
        [ 0.2398, -0.1617,  0.3224,  0.0966, -0.3399],
        [-0.1439,  0.4347,  0.2733, -0.4107,  0.0851]], requires_grad=True)
Parameter containing:
tensor([ 0.2397, -0.2631, -0.4089], requires_grad=True)
Parameter containing:
tensor([[ 0.4214, -0.3373, -0.0726]], requires_grad=True)
Parameter containing:
tensor([-0.3371], requires_grad=True)

In [14]:
from torchinfo import summary
summary(model, input_size=(10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
NNmodule                                 [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

Same architecture using the container model

In [15]:
import torch
import torch.nn as nn

In [17]:
from torch.nn.modules.linear import Linear
from torch.nn.modules.activation import ReLU
class nnModule(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

In [19]:
#create dataset
features = torch.rand(10, 5)

#create model
model = nnModule(features.shape[1])

model(features)

tensor([[0.5057],
        [0.4859],
        [0.4675],
        [0.5049],
        [0.5037],
        [0.4679],
        [0.4891],
        [0.5047],
        [0.4838],
        [0.4848]], grad_fn=<SigmoidBackward0>)

In [20]:
summary(model, input_size=(10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
nnModule                                 [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

Now using the breast cancer data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [3]:
df = pd.read_csv("/content/sample_data/breast_cancer.csv")

In [4]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
df.shape

(569, 31)

In [8]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [9]:
#split into train test
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [10]:
print(X_train.shape)
print(y_train.shape)

(455, 30)
(455,)

In [11]:
#normalize data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_test

array([[ 0.18755831,  1.49776588,  0.12606041, ..., -0.07034783,
        -0.30210132, -0.81907865],
       [-0.50998064, -0.02757344, -0.57258028, ..., -1.15058862,
        -0.57715759, -0.67690499],
       [ 0.58492681, -0.29927451,  0.63695699, ...,  1.12199488,
         2.23234578,  2.22491045],
       ...,
       [-0.47567544, -0.97614383, -0.54225878, ..., -1.13989009,
        -0.0090354 , -0.91707086],
       [-1.14462673, -0.95946043, -1.15907294, ..., -1.6065938 ,
         0.04335627, -0.39935481],
       [-1.24439767, -0.90464355, -1.15824221, ...,  0.66769525,
         0.32987322,  2.37218198]])

In [13]:
#use label encoder for output column
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train

array([0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [15]:
import torch
import torch.nn as nn

In [41]:
#conver it into tensor
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test)

In [31]:
X_train_tensor

tensor([[-0.0526, -0.5996, -0.1119,  ..., -0.8034, -0.3725, -0.3988],
        [ 4.0097, -0.1587,  4.0222,  ...,  0.7049, -2.0605, -1.6296],
        [-0.6987, -0.1920, -0.6851,  ...,  0.1204, -0.1646,  0.3936],
        ...,
        [-0.6701, -1.0596, -0.6378,  ..., -0.1308, -0.4953,  0.8366],
        [-0.1784,  2.1627, -0.2399,  ..., -0.8718, -0.3479, -0.7596],
        [-1.4854, -1.0715, -1.3655,  ..., -1.0261, -1.0683,  1.3809]])

In [47]:
#defining model
class BreastCancer(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 5),
        nn.ReLU(),
        nn.Linear(5, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  #forward pass
  def forward(self, features):
    out = self.network(features)
    return out

In [48]:
#parameters
learing_rate = 0.1
epochs = 25

In [49]:
loss_function = nn.BCELoss()

In [50]:
#create model
model = BreastCancer(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learing_rate)

#define loop
for epoch in range(epochs):
  #forward pass
  y_pred = model(X_train_tensor)

  #loss function
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  #clear
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #optimize
  optimizer.step()

  #loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.6673038005828857
Epoch: 2, Loss: 0.6605992317199707
Epoch: 3, Loss: 0.654184103012085
Epoch: 4, Loss: 0.6481650471687317
Epoch: 5, Loss: 0.6421825289726257
Epoch: 6, Loss: 0.6361795663833618
Epoch: 7, Loss: 0.6298037767410278
Epoch: 8, Loss: 0.6231762766838074
Epoch: 9, Loss: 0.6165236234664917
Epoch: 10, Loss: 0.6100628972053528
Epoch: 11, Loss: 0.6035230159759521
Epoch: 12, Loss: 0.5966733694076538
Epoch: 13, Loss: 0.5896247029304504
Epoch: 14, Loss: 0.5822061896324158
Epoch: 15, Loss: 0.5743207931518555
Epoch: 16, Loss: 0.5660764575004578
Epoch: 17, Loss: 0.5575276613235474
Epoch: 18, Loss: 0.5484558939933777
Epoch: 19, Loss: 0.5389346480369568
Epoch: 20, Loss: 0.5291354060173035
Epoch: 21, Loss: 0.519085168838501
Epoch: 22, Loss: 0.5088794827461243
Epoch: 23, Loss: 0.49866366386413574
Epoch: 24, Loss: 0.48846298456192017
Epoch: 25, Loss: 0.47827866673469543

In [52]:
#evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor.float()).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5507848858833313