<a href="https://colab.research.google.com/github/NishanRegmi/Pytorch/blob/main/pytorch_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [3]:
df = pd.read_csv("/content/sample_data/breast_cancer.csv")
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [6]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [7]:
#train test split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
#scalling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[ 2.17335295,  0.39570669,  2.28096684, ...,  1.08395657,
        -0.08054775,  0.26593677],
       [-0.5764964 , -1.06108434, -0.55825332, ..., -0.73080399,
        -0.22735632, -0.05170115],
       [-0.7267459 , -0.11737694, -0.75092347, ..., -0.76629754,
         0.72689941, -0.77308712],
       ...,
       [-1.06693345, -0.66710941, -1.08010248, ..., -1.36831092,
        -0.34002336, -0.56608071],
       [-0.47727503, -0.362466  , -0.4176451 , ..., -0.60504668,
        -0.55340792,  0.55163983],
       [ 1.18113927,  0.16436095,  1.14544275, ...,  1.22317695,
         0.31207984, -0.01349336]])

In [10]:
y_train

272    M
48     B
55     B
548    B
311    B
      ..
111    B
267    B
546    B
431    B
6      M
Name: diagnosis, Length: 455, dtype: object

In [11]:
#label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

We are about to using pytorch. so we need pytorch tensor

In [13]:
import torch

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [18]:
X_train_tensor.shape

torch.Size([455, 30])

In [17]:
y_train_tensor.shape

torch.Size([455])

Defining model

In [54]:
class SimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  #forward pass
  def forward_pass(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  #loss function
  def loss_funtion(self, y_pred, y):
    #clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #calculate loss
    loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

In [57]:
#important parameters
learning_rate = 0.1
epochs = 25

In [58]:
#training pipeline
#create model
model = SimpleNN(X_train_tensor)

#define loop
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward_pass(X_train_tensor)

  #loss calculate
  loss = model.loss_funtion(y_pred, y_train_tensor)

  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 4.011244245733916
Epoch: 2, Loss: 3.9117477978291104
Epoch: 3, Loss: 3.8054720637981174
Epoch: 4, Loss: 3.697205110828775
Epoch: 5, Loss: 3.581483121153314
Epoch: 6, Loss: 3.4595409724955934
Epoch: 7, Loss: 3.3353813830915717
Epoch: 8, Loss: 3.2019433810121574
Epoch: 9, Loss: 3.063524104574575
Epoch: 10, Loss: 2.92325048057819
Epoch: 11, Loss: 2.7775001855020878
Epoch: 12, Loss: 2.626706193472262
Epoch: 13, Loss: 2.474730541779324
Epoch: 14, Loss: 2.3256037331480943
Epoch: 15, Loss: 2.1730335681775856
Epoch: 16, Loss: 2.0217447857797843
Epoch: 17, Loss: 1.8759839763021668
Epoch: 18, Loss: 1.7272711160126337
Epoch: 19, Loss: 1.5849874831034798
Epoch: 20, Loss: 1.4513261365234258
Epoch: 21, Loss: 1.331060094368367
Epoch: 22, Loss: 1.225281277132425
Epoch: 23, Loss: 1.1346558118844308
Epoch: 24, Loss: 1.0591047627873855
Epoch: 25, Loss: 0.9976172384020248

In [59]:
model.weights

tensor([[-0.0615],
        [ 0.4558],
        [-0.4754],
        [ 0.1669],
        [-0.0875],
        [-0.5295],
        [ 0.1337],
        [-0.1856],
        [ 0.2932],
        [ 0.5656],
        [ 0.4180],
        [ 0.1725],
        [ 0.3929],
        [ 0.1301],
        [-0.0095],
        [ 0.4354],
        [ 0.4584],
        [-0.2222],
        [-0.1096],
        [-0.3109],
        [-0.0758],
        [ 0.3930],
        [-0.4012],
        [ 0.2457],
        [ 0.4897],
        [ 0.0856],
        [ 0.1141],
        [-0.0563],
        [ 0.2122],
        [-0.0832]], dtype=torch.float64, requires_grad=True)

In [60]:
model.bias

tensor([-0.1147], dtype=torch.float64, requires_grad=True)

In [67]:
#evaluation
with torch.no_grad():
  y_pred = model.forward_pass(X_test_tensor)
  y_pred = (y_pred > 0.5).float() #since our actual output is either 0 or 1. so we have to convert the prediction also.

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5012311339378357